name: grofast
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # state manager
  flutter_bloc: ^8.1.6

  # router
  go_router: ^14.2.8

  # dependency injection
  get_it: ^8.0.0

  # equatable
  equatable: ^2.0.5

  # svg pictures
  flutter_svg: ^2.0.10+1

  # rest api
  dio: ^5.7.0

  # assets generator
  flutter_gen: ^5.7.0

  # shimmer effect
  skeletonizer: ^1.4.2

  # intl
  intl: ^0.19.0

  # json annotation
  json_annotation: ^4.9.0

  # sized box
  gap: ^3.0.1

  # google fonts
  google_fonts: ^6.2.1

  # path provide
  path_provider: ^2.1.4

  # dot env
  flutter_dotenv: ^5.1.0

  # connectivity plus
  connectivity_plus: ^6.0.5

  # stream transform
  stream_transform: ^2.1.0

  # bloc concurrency
  bloc_concurrency: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # assets generator
  flutter_gen_runner: ^5.7.0

  # build runner
  build_runner: ^2.4.12

  # json serializable
  json_serializable: ^6.8.0
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3

flutter_gen:
  output: lib/core/utils/gen/
  line_length: 80

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - .env

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: uz
  arb_dir: lib/core/l10n
  output_dir: lib/core/l10n/generated
  use_deferred_loading: false